#!/bin/bash

FILES=../website/static/videos/avi/*.avi
for f in $FILES
do
	echo "Processing $f file..."
	filename=$(basename "$f")
	filename="${filename%.*}"
	echo ffmpeg2theora -o ../website/static/videos/ogv/$filename.ogv --noaudio -v 10 $f
done
