from home_view import home
from protein_list_view import protein_list
from protein_detail_view import protein_detail
from spatiotemporal_views import spatiotemporal_search, spatiotemporal_both, spatiotemporal_compartment, spatiotemporal_timepoint
from network_view import network
from downloads_view import downloads
from downloads_view import downloads_protein
from test_video_view import test_video
